INSERT INTO NOTICE (ID, CONTENT, HITS, LIKES, CREATED_AT, TITLE)
VALUES (default, '내용1', 0, 0, CURRENT_TIMESTAMP ,'제목1');
INSERT INTO NOTICE (ID, CONTENT, HITS, LIKES, CREATED_AT, TITLE)
VALUES (default, '내용2', 0, 0, CURRENT_TIMESTAMP,'제목2');
INSERT INTO NOTICE (ID, CONTENT, HITS, LIKES, CREATED_AT, TITLE)
VALUES (default, '내용3', 0, 0, CURRENT_TIMESTAMP,'제목3');

INSERT INTO NOTICE (ID, CONTENT, HITS, LIKES, CREATED_AT, TITLE)
VALUES (default, '내용4', 0, 0, CURRENT_TIMESTAMP,'제목4');
INSERT INTO NOTICE (ID, CONTENT, HITS, LIKES, CREATED_AT, TITLE)
VALUES (default, '내용5', 0, 0, CURRENT_TIMESTAMP,'제목5');
